services:
  # --- 1. MESSAGE BROKER (Infrastructure) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-central-market

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-central-market

  # --- 2. CONFIG & DISCOVERY (Infrastructure) ---
  config-server:
    image: ${DOCKERHUB_USERNAME}/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", http://localhost:8888/actuator/health]
      interval: 10s
      retries: 5
    networks:
      - microservices-central-market

  eureka-server:
    image: ${DOCKERHUB_USERNAME}/eureka-server:latest
    container_name: eureka-server
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-central-market

  # --- 3. BUSINESS SERVICES (With Database Mapping) ---
  auth-service:
    image: ${DOCKERHUB_USERNAME}/auth-service:latest
    container_name: auth-service
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=${DB_AUTH_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_AUTH_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_AUTH_PASSWORD}
      - SERVER_IP=${SERVER_IP}
    networks:
      - microservices-central-market

  shop-service:
    image: ${DOCKERHUB_USERNAME}/shop-service:latest
    container_name: shop-service
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=${DB_SHOP_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_SHOP_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_SHOP_PASSWORD}
      - SERVER_IP=${SERVER_IP}
    networks:
      - microservices-central-market

  # --- 4. ENTRY POINT ---
  api-gateway:
    image: ${DOCKERHUB_USERNAME}/gateway-service:latest
    container_name: api-gateway
    ports:
      - "9009:9009"
    depends_on:
      auth-service:
        condition: service_started
      shop-service:
        condition: service_started
    networks:
      - microservices-central-market

networks:
  microservices-central-market:
    driver: bridge