# ===================================================================
# API GATEWAY SERVICE
# ===================================================================

server:
  port: 9009
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        # TOKEN RELAY: This is critical!
        # It tells the gateway to take the JWT from the user and pass it to the services.
      default-filters:
        - TokenRelay

      routes:
        #        auth service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**
        #        customer service
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/bis/customers/**
        #        order service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/bis/orders/**
        #        product
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/bis/products/**
        #       catalogue service
        - id: catalogue-service
          uri: lb://CATALOGUE-SERVICE
          predicates:
            - Path=/api/v1/bis/catalogues/**
        #        payment
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/bis/payments/**
        #        shop service
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/api/v1/bis/shops/**, /api/v1/bis/public/shops/**

  #  Auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

# Eureka Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


# LOGGING FOR DEBUGGING ROUTES
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG