# ===================================================================
# SHOP SERVICE CONFIGURATION (Managed by Config Server)
# ===================================================================

server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopdb
    username: sidof
    password: sidof1/@
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Security (OAuth2)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

# Eureka Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# GATEWAY
application:
  config:
    user-url: http://localhost:9009/api/v1/bis/users


