#SERVER
SERVER_PORT: 9010
ACTIVE_PROFILE: dev


#DATASOURSE
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_DATABASE: shopdb
POSTGRES_URL: jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
POSTGRES_PORT: 5433
POSTGRES_PORT_MAPPER: 5334
DB_HOST: localhost


#EMAIL CONFIG
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_ID: sidofdountio@gmail.com
EMAIL_PASSWORD: sa

COMPANY_EMAIL: sidof@sidof.xyz
SECRETKEY: 3521a409ec66d38296f0acc5f264e1541e26336b251bf48d6969e0eabca486cd9eb35f2c30d7eebaebad4867b58cb9f8188714138e05e71e8a173b711eed1768
EXPIRATION: 86400000

#FRONTEND
HOST_SERVER: localhost
ANGULAR_PORT: 30004
VERIFY_EMAIL_HOST: http://localhost${SERVER_PORT}
ACTIVATION_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/activation-account
PASSWORD_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/change-password

ORIGIN: http://localhost:9001



#TLS
TLS: false

#ONSIGNAL
PLAYER_ID: a99d53ee-6d61-4227-bfb0-2c053eaa3673
REST_API_KEY: os_v2_app_vgovh3tnmfbcpp5qfqct5krwoojgnlnin7buwdmnpmq64f4a6m6vhnoasbstqna7okl6jvwjpvls3fc2xgr5yhbvk2wabhl5g5ox7la