# APPLICATION YML FOR FILE  CONFIG SERVER - DEVELOPMENT
server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE