# Application yml in shop service module
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: shop-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE